#!/usr/bin/env bash
#displays the content of the file /etc/passwd.
#only displays username, user id, and Home directory path for the user

f="/etc/passwd"

while IFS= read -r line; do
  echo "$line" | cut -d ':' -f1,3,6
done < "$f"
