#!/usr/bin/env bash
#this script is displaying "Best School" 10 times
#but for the 9th iteration, displays "Best School" and then Hi on a new line.
index="0"
while [ $index -lt 10 ]
do
echo "Best School"
if [ $index -eq 8 ]
then echo "Hi"
fi
index=$((index+1))
done